sudo: required
services:
  - docker

before_install:
  - docker build -t rakeshcheekatimala/react-travis-aws -f Dockerfile.dev .

script:
  - docker run -e CI=true rakeshcheekatimala/react-travis-aws npm run test -- --coverage --watchAll=false

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-489459884699"
  bucket_path: "frontend"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
