sudo: required
services:
  - docker

before_install: 
  - docker build -t lightninglife/sample-docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true lightninglife/sample-docker-react npm run test -- --coverage --watchAll=false

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "EBApp"
  env: "Ebapp-env"
  bucket_name: "s3-bucket-for-sample-docker-react"
  bucket_path: "EBApp"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
