sudo: required
services:
  - docker

before_install:
  - docker build -t rakeshcheekatimala/react-travis-aws -f Dockerfile.dev .

script:
  - docker run rakeshcheekatimala/react-travis-aws npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "Docker-React-AWS"
  env: "DockerReactAws-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-358480227161"
  bucket_path: "Docker-React-AWS"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
